name: cards
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  nfc_manager: ^3.5.0
  http: ^1.4.0
  get_it: ^7.2.0
  provider: ^6.0.5
  lottie: ^3.3.1
  flutter_social_button: ^1.1.6+1
  flutter_bounceable: ^1.2.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  google_sign_in: ^7.1.1
  flutter_facebook_auth: ^7.1.2
  cloud_firestore: ^6.0.1
  loading_animation_widget: ^1.3.0
  fluentui_system_icons: ^1.1.273
  cloud_functions: ^6.0.5
  url_launcher: ^6.3.2
  flutter_web_auth_2: ^4.1.0
  crypto: ^3.0.3
  google_fonts: ^6.2.1

  # âœ… Required for deep link listening (Shopify email login callback -> app)
  app_links: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/placeholder.jpg
